### PR TITLE
Modify pyger to streamline code; add cooldown functionality.

### PR DESCRIPTION
**Pull request by matthewdahmer**
Modify pyger to streamline code; add cooldown functionality.

- Move `ConstraintModel` class to base.py:
The `ConstraintModel` base class code was moved out of the main pyger.py file. Now the pyger.py file is where the custom model classes and other core pyger functions are defined. Splitting up this code into two files makes it easier to maintain, reducing the code one has to scroll through to jump between different parts of the code base. The `ConstraintModel` base class code size will likely double once the "cooldown" functionality is added.

- Move code out of individual model classes, into ConstraintModel base class:
  - In an effort to streamline the pyger code, some functionality that seemed to be repeated in each custom model class was moved out of these custom class defintions and into the `ConstraintModel` base class (e.g. `calc_model`).
  - The `state_only` keyword was removed from `calc_model` since this didn't seem to be used anywhere.

- Separate duration calculation from `calc_dwells1` function:
  - The allowed duration calculation was separated from `calc_dwells1` to simplify the goal of each function, as well as allow these durations to be recalculated using different limits without rerunning the models from scratch. In re-writing the allowed duration calculation routine, this routine was refined to linearly interpolate the precise time allowed instead of selecting the last "good" point.
  - Underscores were added to the function names intended to be used by internal class functions.
  - Minor PEP8 changes were made (mostly whitespace issues).

Note: At the time this pull request was submitted, the cooldown functionality has not yet been added. It is expected that this functionality will be added in further commits to this pull request.

Thank you for reviewing these changes!

### CODE REVIEW

**Comment by taldcroft** [comment]
@matthewdahmer - AFAIK this branch has become the defacto production branch.  Is this PR in shape with appropriate docs and support to be merged back to master?  It would be good to getting back to having official releases of pyger.

**Comment by matthewdahmer** [comment]
@taldcroft - Yes this is the only up-to-date branch. I haven't pushed this to master due to not having the docs updated. I was having an issue with generating the docs via sphinx, but I think I have it worked out now. I just need to get my head back into Pyger mode and plow through the rest of the necessary changes. This is at the top of my to do list once I get through a couple of high priority tasks. I then want to consider a partial re-write to better organize the data generated by Pyger.

**Comment by matthewdahmer** [comment]
@taldcroft - The cooldown branch should now be ready enough to be promoted to master. I'm not happy with some of the features, and the lack of tests, but it works and I'll leave any further significant changes for a new branch. I added what I think are the necessary sphinx documents to at least include the docstrings present in the source files as well as a brief introduction. I left the detailed demo stuff in the Jupyter notebook. I was able to build the HTML files on my local computer; please let me know if you'd like me to post them to the docs folder as well.

**Comment by taldcroft** [comment]
@matthewdahmer - this has gone  past the point where I could meaningfully review, and this branch has been the defacto master for a while.  So :+1: on merging.

The only comment I have is whether you might want to remove the doc/Pyger_Demo.pdf file.  This is essentially a derived product and does not really belong in the git repo.  You could instead plan to generate this file as needed and install to the online docs area if you feel that a PDF version of docs are needed.  I think that in this situation just pointing to the notebooks on GitHub and seeing the online rendered version should be sufficient, but maybe you have a different idea?

If you are game to remove this file from your branch, https://help.github.com/articles/remove-sensitive-data/ is a good resource.  I would definitely test on a separate clone of the repo before doing this on your working copy.

**Comment by matthewdahmer** [comment]
@taldcroft The pdf version of the notebook is a throwback to when notebook files weren't rendered on github. Now that they are rendered, I agree the pdf version of the notebook does not belong. I followed the instructions in your link and have removed the pdf from the repository. I'll go ahead and merge now, will the sphinx docs in the link below be automatically updated?
http://cxc.cfa.harvard.edu/mta/ASPECT/tool_doc/pyger/

**Pull request merged**
